version: "3.1"

services:
  db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: exampledb
      POSTGRES_HOST_AUTH_METHOD: trust # this will  need to go
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  pgdata:
