"""initial migration

Revision ID: 23473ec09916
Revises: e6d1c6c114e7
Create Date: 2024-05-04 14:32:22.077042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 




# revision identifiers, used by Alembic.
revision: str = '23473ec09916'
down_revision: Union[str, None] = 'e6d1c6c114e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stg_role', sa.Column('job_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('stg_role', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stg_role', sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('stg_role', 'job_identifier')
    # ### end Alembic commands ###
