"""initial migration

Revision ID: 47d3b533ab94
Revises: 0579175b0da6
Create Date: 2024-05-04 10:20:19.426641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47d3b533ab94'
down_revision: Union[str, None] = '0579175b0da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stg_role', sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stg_role', sa.Column('team_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stg_role', sa.Column('expectations', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stg_role', sa.Column('responsibilities', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('stg_role', sa.Column('qualifications', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('stg_role', sa.Column('unlimited_pto', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stg_role', 'unlimited_pto')
    op.drop_column('stg_role', 'qualifications')
    op.drop_column('stg_role', 'responsibilities')
    op.drop_column('stg_role', 'expectations')
    op.drop_column('stg_role', 'team_description')
    op.drop_column('stg_role', 'team')
    # ### end Alembic commands ###
