"""initial migration

Revision ID: 76fe74e46337
Revises: 5b5c49a00416
Create Date: 2024-05-04 11:27:24.188907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 




# revision identifiers, used by Alembic.
revision: str = '76fe74e46337'
down_revision: Union[str, None] = '5b5c49a00416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
