"""initial migration

Revision ID: ac9737793148
Revises: f5bde7951ffb
Create Date: 2024-05-03 17:10:42.593521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac9737793148'
down_revision: Union[str, None] = 'f5bde7951ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stg_role', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stg_role', 'extra_data')
    # ### end Alembic commands ###
