"""initial migration

Revision ID: c7ceace60f40
Revises: 76fe74e46337
Create Date: 2024-05-04 12:32:02.876646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 




# revision identifiers, used by Alembic.
revision: str = 'c7ceace60f40'
down_revision: Union[str, None] = '76fe74e46337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stg_role', sa.Column('app_ai_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stg_role', 'app_ai_id')
    # ### end Alembic commands ###
