"""initial migration

Revision ID: d6eaa38b93be
Revises: d820aec32b1c
Create Date: 2024-05-04 10:49:35.256849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 




# revision identifiers, used by Alembic.
revision: str = 'd6eaa38b93be'
down_revision: Union[str, None] = 'd820aec32b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stg_role', sa.Column('posting_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stg_role', sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stg_role', 'industry')
    op.drop_column('stg_role', 'posting_date')
    # ### end Alembic commands ###
