"""initial migration

Revision ID: d820aec32b1c
Revises: 47d3b533ab94
Create Date: 2024-05-04 10:38:19.905326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd820aec32b1c'
down_revision: Union[str, None] = '47d3b533ab94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stg_role', sa.Column('job_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stg_role', sa.Column('employment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stg_role', sa.Column('employment_term_days', sa.Integer(), nullable=True))
    op.add_column('stg_role', sa.Column('tool_experience', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('stg_role', sa.Column('programming_languages', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('stg_role', sa.Column('individual_contributor', sa.Boolean(), nullable=True))
    op.add_column('stg_role', sa.Column('people_manager', sa.Boolean(), nullable=True))
    op.add_column('stg_role', sa.Column('external_links', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stg_role', 'external_links')
    op.drop_column('stg_role', 'people_manager')
    op.drop_column('stg_role', 'individual_contributor')
    op.drop_column('stg_role', 'programming_languages')
    op.drop_column('stg_role', 'tool_experience')
    op.drop_column('stg_role', 'employment_term_days')
    op.drop_column('stg_role', 'employment_type')
    op.drop_column('stg_role', 'job_category')
    # ### end Alembic commands ###
