"""initial migration

Revision ID: e6d1c6c114e7
Revises: 
Create Date: 2024-05-04 14:17:08.318331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6d1c6c114e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stg_role',
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('posting_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employment_term_days', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expectations', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('in_person', sa.Boolean(), nullable=True),
    sa.Column('travel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('responsibilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('qualifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('soft_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tool_experience', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('programming_languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('technical_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('prior_experience_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('individual_contributor', sa.Boolean(), nullable=True),
    sa.Column('people_manager', sa.Boolean(), nullable=True),
    sa.Column('estimated_career_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('education_requirement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compensation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_min_compensation', sa.Integer(), nullable=True),
    sa.Column('estimated_max_compensation', sa.Integer(), nullable=True),
    sa.Column('compensation_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unlimited_pto', sa.Boolean(), nullable=True),
    sa.Column('pto_and_benefits', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role_quirks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_analysis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_links', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('offers_401k', sa.Boolean(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('app_ai_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('app_ai_event_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('specified_context_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('context_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('url_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at_utc', sa.Integer(), nullable=False),
    sa.Column('updated_at_utc', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stg_role')
    # ### end Alembic commands ###
